// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "mc1_scene6",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "mc1_scene6",
            targets: ["AppModule"],
            bundleIdentifier: "sei.study.mc1-scene6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SDWebImage/SDWebImageWebPCoder.git", "0.9.1"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SDWebImageWebPCoder", package: "sdwebimagewebpcoder")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)